version: "3.9"

services:
  web:
    build: .
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 4000:80
    environment:
      - DB_USER=luis
      - DB_PASSWORD=MuchoTexto2023
      - DB_NAME=games
      - DB_HOST=mariadb
    volumes:
      - ./src:/var/www/html
  mariadb:
    healthcheck:
      test: "mariadb -uluis -pMuchoTexto2023"
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MARIADB_USER=luis
      - MARIADB_PASSWORD=MuchoTexto2023
      - MARIADB_DATABASE=games
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql